### ISSUE TITLE
Multi-select binding behaviour incorrect

### ISSUE THREAD

**Issue by jaypha** [nx-js/bind-middleware#2]
Consider the following fragment

```
<select multiple='multiple' name='selly' bind>
<option value='a'>A</option>
<option value='b'>B</option>
</select>
<p> selly is @{selly}</p>
```

In operation, I can select either A, B or both A and B. The state variable `selly`, however, can only be either 'a' or 'b', not both.

Thank you for your time and efforts.
Regards
Jason

**Comment by solkimicreb** [comment]
Thats right multi select is not yet implemented. Data binding uses `HTMLSelectElement.value` for the binding - which is the first selected value in case of a multi select (according to the spec). 

I guess `shelly` should be an array of the selected values, in your case. It needs to be reworked a bit to support this. I would ask if you are interested in submitting a PR, but currently setting up the project locally is pretty painful because of the modular nature (lots of repos) 😄. I plan to make things more community and PR friendly for the next release and i will squeeze in a fix for this too.

Thx for the issue, I will keep it open until the fix arrives!

**Comment by solkimicreb** [comment]
This works as a one way binding in the meantime, if that's enough for your use case:

```js
const map = Array.prototype.map  
nx.components.app()
	.use((comp, state) => {
		state.names = ['John', 'Ann', 'Joe']
		state.onchange = (ev) => {
			state.selected = map.call(ev.target.selectedOptions, option => option.value).join(', ')
		}
	}).register('my-app')
```

```html
<my-app>
  <select name="selected" multiple #change="onchange($event)">
    <option value='John'>John</option>
    <option value='Ann'>Ann</option>
    <option value='Joe'>Joe</option>
  </select>
	<p>@{selected}</p>
</my-app>
```

**Comment by solkimicreb** [comment]
@jaypha I fixed it: https://github.com/nx-js/bindable-middleware/commit/f3bb59fd3525e96e1360acd6de08b4df19b183e9.

Now your example would set `selly` to an array of values. Just run an `npm i` to get the latest version (1.0.2) of the bindable middleware. I will wait to see if it works for you before closing this (:

**Comment by jaypha** [comment]
I just tested the new fix, and this appears to work fine. Thanks.

**Comment by solkimicreb** [comment]
Great! I am closing this issue then.
